# Generated by Django 3.2.8 on 2021-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='47 Spring Street', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='job_satisfaction_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='12345', max_length=5),
            preserve_default=False,
        ),
    ]
