# Generated by Django 3.2.8 on 2021-11-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat_lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
