# Generated by Django 3.2.8 on 2021-11-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_creater',
            new_name='job_creator',
        ),
    ]
