# Generated by Django 3.2.8 on 2021-11-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_job_creater_job_job_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_accepter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
